[package]
name = "vaporetto-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
vaporetto = "=0.6.1"

[build-dependencies]
vaporetto = { version = "=0.6.1", features = ["kytea"] }

[profile.release.build-override]
opt-level = 3
