[package]
name = "vaporetto-deno-bench"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.55"
vaporetto = { version = "=0.2.0", features = ["kytea"] }
wasm-bindgen = "0.2.78"
