[package]
name = "vibrato-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vibrato = { path = "../../thirdparty/vibrato/vibrato", default-features = false, features = ["unchecked"] }

[profile.release.build-override]
opt-level = 3
